"""
Django settings for ses_maker project.

Generated by 'django-admin startproject' using Django 2.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')h0rgw)fug4%m70t73cqyxc80v1fv8lc4%20e^vm-m3qua=k@r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'canteen',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ses_maker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ses_maker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


SESSION_COOKIE_AGE = 60 * 60 * 24

# For easier local development
if int(os.getenv('IS_PRODUCTION', '0')):
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    DEBUG = False

    if int(os.getenv('IS_DAOCLOUD', '0')):
        MIDDLEWARE.insert(0, 'django.middleware.gzip.GZipMiddleware')
        STATIC_ROOT = os.path.join('/vol', 'staticfiles')
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
            'NAME': os.environ['MYSQL_INSTANCE_NAME'],
            'USER': os.environ['MYSQL_USERNAME'],
            'PASSWORD': os.environ['MYSQL_PASSWORD'],
            'HOST': os.environ['MYSQL_PORT_3306_TCP_ADDR'],
            'PORT': os.environ['MYSQL_PORT_3306_TCP_PORT']
        }

    if int(os.getenv('IS_CLOUDFOUNDRY', '0')):
#        import json, dj_database_url
#        url = json.loads(os.environ['VCAP_SERVICES'])['elephantsql'][0]['credentials']['uri']
#        DATABASES['default'] = dj_database_url.parse(url)

        cf_temp_dir = os.getenv('TMPDIR', '/home/vcap/tmp')
        SESSION_ENGINE = 'django.contrib.sessions.backends.file'
        SESSION_FILE_PATH = cf_temp_dir
        STATIC_ROOT = os.path.join(cf_temp_dir, 'staticfiles')
